### PR TITLE
Add TypeScript definitions

### LINKED ISSUE #134: Add TypeScript declarations
As the title says :)
Include the .d.ts file within the package itself or in the [@types](https://github.com/DefinitelyTyped/DefinitelyTyped) repository.

### PR DESCRIPTION
**Pull request by aknuds1**
Cherry-pick of #142, since that has a merge conflict. Thanks @xnevz!

Since the ones from #142 don't work properly, TS type definitions (in the types directory) are automatically generated, by adding the following tsconfig.json and executing `tsc`:

```json
{
  "include": ["lib/**/*"],
  "compilerOptions": {
    "allowJs": true,
    // Generate d.ts files
    "declaration": true,
    "emitDeclarationOnly": true,
    "outDir": "types",
    "declarationMap": true,
    "strict": true
  }
}
```

To test that the type definitions are valid, I've also rewritten the test suite in TypeScript and checked in VS Code.

Fixes #134.

### CODE REVIEW

**Comment by aknuds1** [comment]
@emlynmac do you want to review the TS definitions? I don't really know TS myself.

**Comment by xnevz** [comment]
@aknuds1  happy to be of help !

**Comment by aknuds1** [comment]
It looks to me that the TS definitions are broken, any help would be appreciated:

```
./node_modules/.bin/tsc
lib/camel-case-attribute-names.d.ts:1:1 - error TS1046: Top-level declarations in .d.ts files must start with either a 'declare' or 'export' modifier.

1 const camelCaseMap: { [id: string]: string; };
  ~~~~~

lib/parser.d.ts:1:10 - error TS2614: Module '"./processing-instructions"' has no exported member 'ProcessingInstructions'. Did you mean to use 'import ProcessingInstructions from "./processing-instructions"' instead?

1 import { ProcessingInstructions } from './processing-instructions';
           ~~~~~~~~~~~~~~~~~~~~~~

lib/parser.d.ts:7:2 - error TS1036: Statements are not allowed in ambient contexts.

7 };
   ~

lib/parser.d.ts:11:30 - error TS2552: Cannot find name 'ReactElement'. Did you mean 'SVGRectElement'?

11     parse: (html: string) => ReactElement;
                                ~~~~~~~~~~~~

  node_modules/typescript/lib/lib.dom.d.ts:13312:13
    13312 declare var SVGRectElement: {
                      ~~~~~~~~~~~~~~
    'SVGRectElement' is declared here.

lib/processing-instructions.d.ts:2:10 - error TS2614: Module '"./process-node-definitions"' has no exported member 'processDefaultNode'. Did you mean to use 'import processDefaultNode from "./process-node-definitions"' instead?

2 import { processDefaultNode } from "./process-node-definitions";
           ~~~~~~~~~~~~~~~~~~


Found 5 errors in 3 files.
```

**Comment by aknuds1** [comment]
Since I found that the TS type definitions from #142 wouldn't compile, I've committed and pushed automatically generated type definitions in the types/ directory instead. I generated them by adding the following tsconfig.json and executing `tsc`:

```json
{
  "include": ["lib/**/*"],
  "compilerOptions": {
    "allowJs": true,
    // Generate d.ts files
    "declaration": true,
    "emitDeclarationOnly": true,
    "outDir": "types",
    "declarationMap": true
  }
}
```

To test that the type definitions are valid, I've also rewritten the test suite in TypeScript.

**Comment by emlynmac** [comment]
The auto-generated TS definitions are a little weak - the definitions are basically using `any` which doesn't have any type-checking.
I think this week I'm not gonna have time to look at this properly, but hopefully next I can find some time to go over this more thoroughly.

**Comment by aknuds1** [comment]
Thank you @emlynmac - that would be great.

**Comment by emlynmac** [comment]
I had a chance to look through the library for types today, need to get it hooked into my project.
I'm using an overlay in that project and the file is:
```
declare module 'html-to-react' {
  import { ParserOptions } from 'htmlparser2';
  import { ReactElement } from 'react';

  function Html2ReactParser(options: ParserOptions): {
    parse: (html: string) => ReactNode | ReactNode[];
    parseWithInstructions: (
      html: string,
      isValidNode: (node: ReactNode) => boolean,
      processingInstructions?: ProcessingInstructionType[],
      preprocessingInstructions?: ProcessingInstructionType[]
    ) => ReactNode | ReactNode[];
  };

  function createElement(node: ReactNode, index: number, data: any, children: ReactNode[]): ReactNode;

  type ProcessingInstructionType = {
    shouldProcessNode: (node: ReactNode) => boolean;
    processNode: (node: ReactNode, children: ReactNode[], index: number) => ReactNode | ReactNode[];
  };
  function ProcessingInstructions(): {
    defaultProcessingInstructions: ProcessingInstructionType[];
  };

  function ProcessNodeDefinitions(): {
    processDefaultNode: (node: ReactNode, children: ReactNode[], index: number) => ReactNode | ReactNode[];
  };

  const IsValidNodeDefinitions: {
    alwaysValid(): boolean;
  };

  export { Html2ReactParser as Parser, ProcessingInstructions, IsValidNodeDefinitions, ProcessNodeDefinitions };
}
```

I am not certain that this covers all the cases 100%, please have a review and see what you think.

**Comment by emlynmac** [comment]
I got a chance to look at this today and have an overlay type definition for local use:

```
declare module 'html-to-react' {
  import { ParserOptions } from 'htmlparser2';
  import React, { ReactNode } from 'react';

  function Html2ReactParser(options: ParserOptions): {
    parse: (html: string) => JSX.Element;
    parseWithInstructions: (
      html: string, 
      isValidNode: (node: any) => boolean, 
      processingInstructions?: ProcessingInstructionType[], 
      preprocessingInstructions?: ProcessingInstructionType[]
    ) => JSX.Element;
  };

  export type ProcessNodeFunctionType = (
    node: React.DOMElement, 
    children: any, 
    index: number
  ) => ReactNode | ReactNode[];
  
  export type ProcessingInstructionType = {
    shouldProcessNode: (node: any) => boolean;
    processNode: ProcessNodeFunctionType;
  }

  function ProcessingInstructions(): {
    defaultProcessingInstructions: ProcessingInstructionType;
  }

  function ProcessNodeDefinitions(): {
    processDefaultNode: ProcessNodeFunctionType;
  };

  const IsValidNodeDefinitions: {
    alwaysValid(): boolean;
  }

  export { 
    Html2ReactParser as Parser, 
    ProcessingInstructions, 
    IsValidNodeDefinitions, 
    ProcessNodeDefinitions 
  };
}
```

**Comment by emlynmac** [comment]
I added #148 to cover the version I put together.

**Pull request merged**
