### PR TITLE
Add a way to pass options to processNode functions

### PR DESCRIPTION
**Pull request by austinhollenbaugh**
We need the ability to pass an onClick function to be added to an element that is being created by one of our `processNode` funcs. 

I just passed an optional param to `processNode`, to allow for this.

### CODE REVIEW

**Comment by austinhollenbaugh** [comment]
We need `processNode` to be able to return a fully functional component, including props that have been passed to it. In this case specifically we need the ability to add an `onClick` function to the component that is being returned from `processNode`. As far as I can tell right now there is no way to do that.

I went ahead and updated the PR to instead pass the args through `parseWithInstructions`, which passes them directly to `traverseDom` where we can pass them to `processNode`.

**Comment by aknuds1** [comment]
Instad of passing the arguments via `parseWithInstructions` (or `traverseDom`) I thought it would be a better API to specify them via individual processing instructions (`processingInstructions`) in your test case.

That said, can't you also also solve your case by including a function in your processing instruction that passes the required properties (e.g. `onClick`) to the component you're creating?

**Comment by aknuds1** [comment]
@austinhollenbaugh The following is an example of what I mean: 

```
const processingInstructions = [{
  shouldProcessNode: function (node) { return true; },
  processNode: function (el, children, index) {
    return React.createElement('div', {onclick: () => {
      console.log(`Clicked!`);
    }});
  },
},];
const reactComponent = parser.parseWithInstructions(
  htmlInput,
  function () { return true; },
  processingInstructions,
);
```

Can you tell me if you have a need which isn't covered by the above code?

**Comment by aknuds1** [comment]
Can I close this PR by now?

**Comment by aknuds1** [comment]
Closing this on account of inactivity.

**Pull request closed without merging**
