### PR TITLE
Update utils.js ( Failing on production code and working fine on localHost)

### PR DESCRIPTION
**Pull request by kkrishna00**
// value = Function(value); this is giving error on production code. Earlier versions are working are fine.
 // Error - SyntaxError: Function statements require a function name

### CODE REVIEW

**Review by aknuds1 — CHANGES_REQUESTED** [review]
Your PR breaks a test 

```
1) Html2React
       parse valid HTML
         should handle onclick attributes:

      AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
+ actual - expected

+ 'string'
- 'function'
      + expected - actual

      -string
      +function
      
      at Context.<anonymous> (test/html-to-react-tests.js:277:14)
      at processImmediate (node:internal/timers:464:21)
```

Do you have an example of how to reproduce your bug? Your report looks like #133.

**Comment by kkrishna00** [comment]
html is really big 
earlier versions are working fine
But this is breaking in this version

**Comment by kkrishna00** [comment]
html is coming from google doc api

**Comment by aknuds1** [comment]
Closing this as duplicate of #133 (and also breaking test suite) until I see proof of the opposite.

**Pull request closed without merging**
