### PR TITLE
Added typescript types.

### PR DESCRIPTION
**Pull request by xnevz**
Added typescript type support for ease of with React Projects.

### CODE REVIEW

**Comment by emlynmac** [comment]
Should these types be kept over at definitely typed instead of in this repository?
https://github.com/DefinitelyTyped/DefinitelyTyped#how-can-i-contribute

**Comment by aknuds1** [comment]
Do you mind if I fix the package.json conflict and push?

**Comment by aknuds1** [comment]
@emlynmac is the normal approach to keep type definitions at Definitely Typed instead?

**Comment by emlynmac** [comment]
@aknuds1 It depends on the package owner :) 

If the JS library owner is good with taking on the TS definitions and owning the changes, then that's the best solution. Keep the definitions in lock-step with the library releases.

Sometimes, JS libraries don't want to take on the TS definitions, so then the solution is provide the types as an overlay at the @types/<def>

**Comment by aknuds1** [comment]
@emlynmac I think it would be OK to keep TS definitions in this repo, with the caveat that I'm not experienced in TypeScript. The library's interface is so stable though, that it's probably not much of a problem.

**Comment by aknuds1** [comment]
Due to the merge conflict in this PR, I wonder if I should just make my own PR cherry-picking from this one.

**Comment by aknuds1** [comment]
@xnevz @emlynmac I've made another [PR](https://github.com/aknuds1/html-to-react/pull/146) cherry-picking from this PR, in order to get around the merge conflict in this PR. Also upgrading TypeScript to v5.

**Comment by xnevz** [comment]
Yes go ahead, Feel free to cherry-pick, happy to be of help !

**Comment by xnevz** [comment]
Yes go ahead, Feel free to cherry-pick, happy to be of help !

**Pull request closed without merging**
