### PR TITLE
fix: processing bool attr while parsing (#129)

### PR DESCRIPTION
**Pull request by ArtemNizelnyk**
Fix for  #129 

@aknuds1

### CODE REVIEW

**Comment by aknuds1** [comment]
You need to introduce a test case corresponding to the bug you're aiming to fix.

**Comment by ArtemNizelnyk** [comment]
> You need to include a test case corresponding to the bug you're aiming to fix.

Done.

**Comment by aknuds1** [comment]
Based on your test, I've considered what the actual bug is and I can confirm that certain value-less attributes such as `readonly` indeed don't work (since the corresponding React attributes are in camelCase).

I think there's a better way of solving it though, i.e. to make make the React attribute names the reference and also to have the test try _all_ boolean attributes. Please update your PR to match my [branch](https://github.com/aknuds1/html-to-react/tree/bugfix/boolean-attrs) and I'll approve.

**Review by aknuds1 — CHANGES_REQUESTED** [review]
Based on your test, I've considered what the actual bug is and I can confirm that certain value-less attributes such as readonly indeed don't work (since the corresponding React attributes are in camelCase).

I think there's a better way of solving it though, i.e. to make make the React attribute names the reference and also to have the test try all boolean attributes. Please update your PR to match my branch and I'll approve.

**Comment by aknuds1** [comment]
Thanks, but closing this PR since it's been 11 days since I requested changes. I merged my own changes instead.

**Pull request closed without merging**
